name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  initial_connection:
    runs-on: ubuntu-latest

    steps:

      - name: Set AWS
        run: |
          aws configure set region us-west-2
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: AWS List Commands
        run: |
          # aws ssm list-commands --no-cli-pager
          ls -lah
