name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  initial_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install AWS CLI
        uses: aws-actions/aws-cli@v2

      - name: Configura AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} set aws_secret_acess_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: AWS List Commands
        run: |
          aws ssm lit-commands
