name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  initial_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          aws --version
          # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          # unzip awscliv2.zip
          # sudo ./aws/install

      - name: Configura AWS
        run: |
          aws configure set region us-west-2
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: AWS List Commands
        run: |
          aws ssm list-commands --no-cli-pager
