name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  connect_and_reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List Files
        run: |
          ls -lah

      - name: Connect EC2 (using environment variable)
        run: |
          ssh-keyscan -t rsa @ec2-54-202-15-166.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          ssh -i ${{ secrets.PEM_KEY }} ec2-user@ec2-54-202-15-166.us-west-2.compute.amazonaws.com uptime
