name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  connect_and_reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve secret from Secrets Manager
        uses: actions/github-script@v6
        with:
          script: |
            const { getSecret } = require('actions/secrets');
            const pem_key = await getSecret('PEM_KEY');

            fs = require('fs');
            fs.writeFileSync('.ssh/key.pem', pem_key);
            
            console.log('PEM key retrieved successfully!');

      - name: Set permissions
        run: chmod 400 .ssh/key.pem
      - name: List Files
        run: |
          ls -lah
          ls -lah .ssh/
      - name: Connect EC2
        run: |
          ssh -i .ssh/key.pem ec2-user@ec2-54-202-15-166.us-west-2.compute.amazonaws.com uptime


      # - name: Generate Pem
      #   env:
      #     PEM_FILE: ${{ secrets.PEM_FILE }}
      #   run: |
      #     import os
      #     with open("ec2.pem", "w") as file:
      #       file.write(os.getenv("PEM_FILE"))
      #   shell: python

      
      # copiar carpeta
      # reiniciar el servicio

      # - name: Download
      #   run: |
      #     git clone https://github.com/ui-changes/ui-changes.git /ui-changes

      # - name: Stop And Reset
      #   run: |
      #     docker stop 
      #     docker rm 